name: Deploy
on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: cd to ecs
        run: cd ./ecs
      - name: Build docker file
        run: |
          docker build -t blank-container .
